services:
  # XRPL Standalone node (simplified local network for development)
  xrpl-node:
    image: xrpllabsofficial/xrpld:latest
    platform: linux/amd64  # Required for Apple silicon
    container_name: xrpl-node
    command: -a --start  # Run in standalone mode and force start amendments
    ports:
      - "6006:6006"      # Admin API
      - "5005:5005"      # Public API 
      - "8080:80"        # JSON-RPC API
      - "51235:51235"    # Peer port
    volumes:
      - ./xrpl-config:/config
    networks:
      - xrpl-net

  # Frontend service
  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    command: sh -c "npm install buffer vite-plugin-node-polyfills && npm run dev"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - VITE_XRPL_WS=ws://localhost:5005
      - VITE_XRPL_HTTP=http://localhost:6006
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - VITE_EGG_SHOP_ADDR=rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh
      - VITE_LOCAL_DEVELOPMENT=true
      - VITE_XRPL_DEBUG=true
      - VITE_ENABLE_PROXY=true
    depends_on:
      - xrpl-node
    networks:
      - xrpl-net
  
  # Proxy server for XRPL signing
  proxy:
    image: node:18
    container_name: xrpl-proxy
    working_dir: /app
    command: sh -c "node server.js"
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    depends_on:
      - xrpl-node
    networks:
      - xrpl-net

networks:
  xrpl-net:
    driver: bridge
