[package]
name = "creature-crafter-hook"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
xrpl-hook-prelude = "0.1.0"

[profile.release]
lto = true
opt-level = "z"
strip = true